version: '3'
services:
  mqqt:
    build: .
    image: "eclipse-mosquitto"
    ports:
      - "1883:1883"
      - "9001:9001"
  redis:
    image: "redis:alpine"


# docker run -it -p 1883:1883 -p 9001:9001 -v mosquitto.conf:/mosquitto/config/mosquitto.conf eclipse-mosquitto